branches:
  only:
    - master
language: node_js
node_js:
  - 10
git:
  depth: 3
install:
  - yarn --frozen-lockfile
  - yarn lint --fix
  - yarn test
cache: yarn
after_script:
  - sh build/deploy-theme.sh
  - sh ./notify.sh
